#!/bin/dash

# =====================================
# Syntax checking
# =====================================
default_repo=".pig"

if ! test -d "$default_repo"
then
    echo "$0: error: pigs repository directory $default_repo not found" >&2
    exit 1
fi 

if [ "$#" -eq 0 ] || [ "$#" -gt 1 ]
then
    echo "usage: pigs-checkout <branch>" >&2
    exit 1
fi 

# =====================================
# Main
# =====================================

if ! grep -E "^$1 .*$" "$default_repo/BRANCHES" > /dev/null
then
    echo "$0: error: unknown branch '$1'" >&2
    exit 1
fi 

if [ "$(cat "$default_repo/HEAD")" = "$1" ]
then
    echo "Already on '$1'"
    exit 0
fi 

# populate file
target_tree=$(grep -E "^$1 .*$" "$default_repo/BRANCHES" | cut -d' ' -f2)
target_tree_file="$default_repo/objects/$target_tree"

# dangerous
rm ./*

while IFS= read -r line
do 
    file_content=$(echo "$line" | cut -d' ' -f2)
    cat "$default_repo/objects/$file_content" > "$(echo "$line" | cut -d' ' -f1)"
done < "$target_tree_file"

curr_branch=$(cat "$default_repo"/HEAD)
cat "$default_repo/logs/$curr_branch" > "$default_repo/logs/$1"

# switch branch
echo "$1" > "$default_repo/HEAD"
echo "Switched to branch '$1'"
