#!/bin/dash

pigs_dir=".pig"

if test -e "$pigs_dir"
then
    echo "$0: error: $pigs_dir already exists" >&2
    exit 1
fi

mkdir "$pigs_dir"

# initialize index file
touch "$pigs_dir/index"

# initialize object file
mkdir "$pigs_dir/objects"

default_branch_name="master"

# initialize branch infos
empty_file=$(mktemp)
empty_hash=$(sha1sum "$empty_file" | cut -d' ' -f1)
rm "$empty_file"

echo "$default_branch_name $empty_hash" > "$pigs_dir/BRANCHES"
touch "$pigs_dir/objects/$empty_hash"

# initialize curr head
echo "$default_branch_name" > "$pigs_dir/HEAD"

# initialize log file
mkdir "$pigs_dir/logs"
touch "$pigs_dir/logs/$default_branch_name"
touch "$pigs_dir/logs/COMMIT_NUM"

# initialize commit history
mkdir "$pigs_dir/commits"
touch "$pigs_dir/commits/$default_branch_name"

# to store files to ignore when constructing new tree (git rm)
touch "$pigs_dir/removes"

# not really empty lol
echo "Initialized empty pigs repository in $pigs_dir"
