#!/bin/dash

# =====================================
# Syntax checking
# =====================================
default_repo=".pig"

if ! test -d "$default_repo"
then
    echo "$0: error: pigs repository directory $default_repo not found" >&2
    exit 1
fi 

if [ $# -eq 0 ]
then
    echo "usage: $0 <filenames>" >&2
    exit 1
fi

# ======================================
# Main
# ======================================
index_file="./$default_repo/index"
objects_file="./$default_repo/objects"

# check if file exist in index, or current directory
for file in "$@"
do
    if ! (grep -E "^$file" "$index_file" > /dev/null || test -f "$file")
    then
        echo "$0: error: can not open '$file'" >&2
        exit 1
    fi 
done 

for file in "$@"
do 
    # might introduce lost pointers, might fix if i have time
    if ! test -f "$file"
    then
        continue
    fi 

    content_hash="$(sha1sum "$file" | cut -d' ' -f1)"

    if [ -z "$(cat "$file")" ]
    then
        : >  "$objects_file/$content_hash"
    else 
        cat "$file" > "$objects_file/$content_hash"
    fi 

    if grep -E "^$file" "$index_file" > /dev/null
    then
        tmp=$(sed -E "s/^$file .*$/$file $content_hash/" "$index_file")

        if [ -n "$tmp" ]
        then 
            echo "$tmp" > "$index_file"
        else 
            : > "$index_file"
        fi 
    else 
        echo "$file $content_hash" >> "$index_file"
    fi 
done 
